ConnectionStrings: 
    ReportsConnection: conexion_reportes
ServicesUrl:
    ProductApiUrl: http://Microservices.Demo.Product.API/api/products
    PolicyApiUrl: http://Microservices.Demo.Policy.API/api/policies 